# -*- coding: utf-8 -*-
"""Hard_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsnQg_TUxc9tpZrknXRliGBYkttCuE9b
"""

!pip install torch scikit-learn matplotlib seaborn umap-learn plotly -q
!pip install torchvision pillow -q
!pip install scipy -q

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score, adjusted_rand_score, normalized_mutual_info_score
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import os

"""DATA LOADING"""

from google.colab import drive
drive.mount('/content/drive')

project_path = '/content/drive/MyDrive/Data/Features'
X_train = np.load(os.path.join(project_path, 'X_train.npy'))  # Audio features (800 x 13)
y_train = np.load(os.path.join(project_path, 'y_train.npy'))  # Genre labels
X_hybrid = np.load(os.path.join(project_path, 'X_hybrid.npy'))  # Hybrid audio + lyrics (800 x 63)

print(f"   Audio features: {X_train.shape}")
print(f"   Hybrid features: {X_hybrid.shape}")
print(f"   Labels: {y_train.shape}")

"""Define genre names and create one-hot encoding"""

def one_hot_encode(labels, num_classes=10):
    return np.eye(num_classes)[labels]
X_tensor = torch.FloatTensor(X_hybrid)
y_one_hot = one_hot_encode(y_train)
y_tensor = torch.FloatTensor(y_one_hot)

# Genre names (must match your dataset)
genre_names = ['blues', 'classical', 'country', 'disco', 'hiphop',
               'jazz', 'metal', 'pop', 'reggae', 'rock']

print(f"   X_tensor: {X_tensor.shape}")
print(f"   y_tensor: {y_tensor.shape}")
print(f"   One-hot labels: {y_one_hot.shape}")

"""#Implement Beta-VAE ( on EnhancedVAE with tunable beta)"""

class BetaVAE(nn.Module):
    """Beta-VAE with tunable beta for disentanglement"""
    def __init__(self, input_dim=63, hidden_dims=[128, 64, 32], latent_dim=20):
        super(BetaVAE, self).__init__()

        # Encoder layers
        encoder_layers = []
        prev_dim = input_dim
        for hidden_dim in hidden_dims:
            encoder_layers.append(nn.Linear(prev_dim, hidden_dim))
            encoder_layers.append(nn.BatchNorm1d(hidden_dim))
            encoder_layers.append(nn.ReLU())
            encoder_layers.append(nn.Dropout(0.2))
            prev_dim = hidden_dim

        self.encoder = nn.Sequential(*encoder_layers)

        # Latent space
        self.fc_mu = nn.Linear(hidden_dims[-1], latent_dim)
        self.fc_logvar = nn.Linear(hidden_dims[-1], latent_dim)

        # Decoder layers
        decoder_layers = []
        decoder_dims = [latent_dim] + hidden_dims[::-1]

        for i in range(len(decoder_dims) - 1):
            decoder_layers.append(nn.Linear(decoder_dims[i], decoder_dims[i+1]))
            decoder_layers.append(nn.BatchNorm1d(decoder_dims[i+1]))
            decoder_layers.append(nn.ReLU())
            decoder_layers.append(nn.Dropout(0.2))

        decoder_layers.append(nn.Linear(decoder_dims[-1], input_dim))
        self.decoder = nn.Sequential(*decoder_layers)

    def encode(self, x):
        h = self.encoder(x)
        return self.fc_mu(h), self.fc_logvar(h)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

"""Train Beta-VAE"""

def train_beta_vae(model, X_data, epochs=150, lr=0.001, beta=4.0):
    optimizer = optim.Adam(model.parameters(), lr=lr)
    train_losses = []
    recon_losses = []
    kl_losses = []

    X_tensor = torch.FloatTensor(X_data)

    for epoch in range(epochs):
        recon_x, mu, logvar = model(X_tensor)
        recon_loss = nn.MSELoss()(recon_x, X_tensor)
        kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
        loss = recon_loss + beta * kl_loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_losses.append(loss.item())
        recon_losses.append(recon_loss.item())
        kl_losses.append(kl_loss.item())

        if (epoch + 1) % 50 == 0:
            print(f"  Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}, Recon: {recon_loss.item():.4f}, KL: {kl_loss.item():.4f}")

    return model, train_losses, recon_losses, kl_losses

input_dim = X_hybrid.shape[1]
latent_dim = 20
beta_vae = BetaVAE(input_dim=input_dim, latent_dim=latent_dim)
trained_beta_vae, losses, recon_losses, kl_losses = train_beta_vae(beta_vae, X_hybrid, epochs=150, beta=4.0)

"""#Conditional VAE"""

class CVAE(nn.Module):
    """Conditional VAE conditioned on genre for multi-modal integration"""
    def __init__(self, input_dim=63, cond_dim=10, hidden_dims=[128, 64, 32], latent_dim=20):
        super(CVAE, self).__init__()

        # Encoder: input + cond
        encoder_layers = []
        prev_dim = input_dim + cond_dim
        for hidden_dim in hidden_dims:
            encoder_layers.append(nn.Linear(prev_dim, hidden_dim))
            encoder_layers.append(nn.BatchNorm1d(hidden_dim))
            encoder_layers.append(nn.ReLU())
            encoder_layers.append(nn.Dropout(0.2))
            prev_dim = hidden_dim

        self.encoder = nn.Sequential(*encoder_layers)

        self.fc_mu = nn.Linear(hidden_dims[-1], latent_dim)
        self.fc_logvar = nn.Linear(hidden_dims[-1], latent_dim)

        # Decoder: latent + cond
        decoder_layers = []
        prev_dim = latent_dim + cond_dim
        for hidden_dim in hidden_dims[::-1]:
            decoder_layers.append(nn.Linear(prev_dim, hidden_dim))
            decoder_layers.append(nn.BatchNorm1d(hidden_dim))
            decoder_layers.append(nn.ReLU())
            decoder_layers.append(nn.Dropout(0.2))
            prev_dim = hidden_dim

        decoder_layers.append(nn.Linear(prev_dim, input_dim))
        self.decoder = nn.Sequential(*decoder_layers)

    def encode(self, x, cond):
        h = self.encoder(torch.cat([x, cond], dim=1))
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        logvar = torch.clamp(logvar, min=-10, max=10)  # Stabilize
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z, cond):
        return self.decoder(torch.cat([z, cond], dim=1))

    def forward(self, x, cond):
        mu, logvar = self.encode(x, cond)
        z = self.reparameterize(mu, logvar)
        return self.decode(z, cond), mu, logvar

# Initialize
input_dim = X_hybrid.shape[1]
cond_dim = y_one_hot.shape[1]
latent_dim = 20
cvae = CVAE(input_dim=input_dim, cond_dim=cond_dim, latent_dim=latent_dim)

"""Train CVAE"""

def train_cvae(model, X_data, y_cond, epochs=150, lr=0.001, beta=4.0):
    optimizer = optim.Adam(model.parameters(), lr=lr)
    train_losses = []
    recon_losses = []
    kl_losses = []

    X_tensor = torch.FloatTensor(X_data)
    y_tensor = torch.FloatTensor(y_cond)

    for epoch in range(epochs):
        recon_x, mu, logvar = model(X_tensor, y_tensor)
        recon_loss = nn.MSELoss()(recon_x, X_tensor)
        kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
        loss = recon_loss + beta * kl_loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_losses.append(loss.item())
        recon_losses.append(recon_loss.item())
        kl_losses.append(kl_loss.item())

        if (epoch + 1) % 50 == 0:
            print(f"  Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}, Recon: {recon_loss.item():.4f}, KL: {kl_loss.item():.4f}")

    return model, train_losses, recon_losses, kl_losses

trained_cvae, losses, recon_losses, kl_losses = train_cvae(cvae, X_hybrid, y_one_hot, epochs=150, beta=4.0)

"""Implement Autoencoder for comparison"""

class Autoencoder(nn.Module):
    def __init__(self, input_dim=63, hidden_dims=[128, 64, 32], latent_dim=20):
        super(Autoencoder, self).__init__()

        # Encoder
        encoder_layers = []
        prev_dim = input_dim
        for hidden_dim in hidden_dims:
            encoder_layers.append(nn.Linear(prev_dim, hidden_dim))
            encoder_layers.append(nn.BatchNorm1d(hidden_dim))
            encoder_layers.append(nn.ReLU())
            encoder_layers.append(nn.Dropout(0.2))
            prev_dim = hidden_dim
        encoder_layers.append(nn.Linear(prev_dim, latent_dim))
        self.encoder = nn.Sequential(*encoder_layers)

        # Decoder
        decoder_layers = []
        prev_dim = latent_dim
        for hidden_dim in reversed(hidden_dims):
            decoder_layers.append(nn.Linear(prev_dim, hidden_dim))
            decoder_layers.append(nn.BatchNorm1d(hidden_dim))
            decoder_layers.append(nn.ReLU())
            decoder_layers.append(nn.Dropout(0.2))
            prev_dim = hidden_dim
        decoder_layers.append(nn.Linear(prev_dim, input_dim))
        self.decoder = nn.Sequential(*decoder_layers)

    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z)

def train_ae(model, X_data, epochs=150, lr=0.001):
    optimizer = optim.Adam(model.parameters(), lr=lr)
    losses = []

    X_tensor = torch.FloatTensor(X_data)

    for epoch in range(epochs):
        recon_x = model(X_tensor)
        loss = nn.MSELoss()(recon_x, X_tensor)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        losses.append(loss.item())

        if (epoch + 1) % 50 == 0:
            print(f"  Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

    return model, losses

ae = Autoencoder(input_dim=input_dim, latent_dim=latent_dim)
trained_ae, ae_losses = train_ae(ae, X_hybrid)

"""Extract latent features from Beta-VAE and AE"""

def extract_latent_beta(model, X_data):
    with torch.no_grad():
        mu, _ = model.encode(torch.FloatTensor(X_data))
        return mu.numpy()

def extract_latent_cvae(model, X_data, y_cond):
    with torch.no_grad():
        mu, _ = model.encode(torch.FloatTensor(X_data), torch.FloatTensor(y_cond))
        return mu.numpy()

latent_beta = extract_latent_beta(beta_vae, X_hybrid)
latent_cvae = extract_latent_cvae(cvae, X_hybrid, y_one_hot)

print(f"   Beta-VAE latent: {latent_beta.shape}")
print(f"   CVAE latent:     {latent_cvae.shape}")

"""Baselines - PCA and Direct features"""

pca = PCA(n_components=20)
latent_pca = pca.fit_transform(X_hybrid)
latent_direct = X_hybrid  # raw hybrid features

"""clustering algorithms //multi-modal on hybrid latent"""

def apply_clustering(X, n_clusters=10):
    results = {}
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    results['K-Means'] = kmeans.fit_predict(X)

    agglomerative = AgglomerativeClustering(n_clusters=n_clusters, linkage='ward')
    results['Agglomerative'] = agglomerative.fit_predict(X)

    neighbors = NearestNeighbors(n_neighbors=5)
    distances, _ = neighbors.fit(X).kneighbors(X)
    distances = np.sort(distances[:, -1])
    eps = np.percentile(distances, 90)
    dbscan = DBSCAN(eps=eps, min_samples=5)
    dbscan_labels = dbscan.fit_predict(X)
    dbscan_labels[dbscan_labels == -1] = np.max(dbscan_labels) + 1 if np.max(dbscan_labels) >= 0 else 0
    results['DBSCAN'] = dbscan_labels

    return results

clustering_beta_vae = apply_clustering(latent_beta_vae)
clustering_ae = apply_clustering(latent_ae)

# For comparisons
pca = PCA(n_components=20)
pca_features = pca.fit_transform(X_hybrid)
clustering_pca = apply_clustering(pca_features)['K-Means']  # Only K-Means for PCA

direct_features = X_hybrid  # Or X_train for spectral
clustering_direct = apply_clustering(direct_features)['K-Means']  # K-Means on direct features

"""Define cluster purity metric"""

def cluster_purity(y_true, y_pred):
    contingency = pd.crosstab(y_true, y_pred)
    majority = contingency.max(axis=0)
    return majority.sum() / len(y_true)

"""Evaluate clustering with all metrics"""

def evaluate_clustering(X, labels, true_labels):
    metrics = {}
    metrics['Silhouette'] = silhouette_score(X, labels)
    metrics['Davies-Bouldin'] = davies_bouldin_score(X, labels)
    metrics['ARI'] = adjusted_rand_score(true_labels, labels)
    metrics['NMI'] = normalized_mutual_info_score(true_labels, labels)
    metrics['Purity'] = cluster_purity(true_labels, labels)
    return metrics

evaluation_beta_vae = {}
for algo, labels in clustering_beta_vae.items():
    evaluation_beta_vae[algo] = evaluate_clustering(latent_beta_vae, labels, y_train)

# Similarly for others
evaluation_ae = evaluate_clustering(latent_ae, clustering_ae['K-Means'], y_train)
evaluation_pca = evaluate_clustering(pca_features, clustering_pca, y_train)
evaluation_direct = evaluate_clustering(direct_features, clustering_direct, y_train)

# Print Beta-VAE results
print("Beta-VAE Clustering Results:")
comparison_df = pd.DataFrame.from_dict({algo: metrics for algo, metrics in evaluation_beta_vae.items()}, orient='index')
print(comparison_df)

# Comparisons
print("\nComparisons (K-Means):")
comp_data = {
    'Method': ['Beta-VAE', 'AE', 'PCA', 'Direct'],
    'Silhouette': [evaluation_beta_vae['K-Means']['Silhouette'], evaluation_ae['Silhouette'], evaluation_pca['Silhouette'], evaluation_direct['Silhouette']],
    'ARI': [evaluation_beta_vae['K-Means']['ARI'], evaluation_ae['ARI'], evaluation_pca['ARI'], evaluation_direct['ARI']],
    'NMI': [evaluation_beta_vae['K-Means']['NMI'], evaluation_ae['NMI'], evaluation_pca['NMI'], evaluation_direct['NMI']],
    'Purity': [evaluation_beta_vae['K-Means']['Purity'], evaluation_ae['Purity'], evaluation_pca['Purity'], evaluation_direct['Purity']]
}
comp_df = pd.DataFrame(comp_data)
print(comp_df)

"""Visualizations - Latent space plots

ADVANCED LATENT SPACE VISUALIZATIONS
"""

# Use CVAE latent (best expected performance)
pca2 = PCA(n_components=2)
tsne = TSNE(n_components=2, random_state=42, perplexity=30)
umap_red = umap.UMAP(n_components=2, random_state=42)

latent_pca2 = pca2.fit_transform(latent_cvae)
latent_tsne = tsne.fit_transform(latent_cvae[:500])  # subsample for speed
latent_umap = umap_red.fit_transform(latent_cvae)

fig, axes = plt.subplots(2, 3, figsize=(18, 12))

# Row 1: Colored by true genre
axes[0,0].scatter(latent_pca2[:,0], latent_pca2[:,1], c=y_train, cmap='tab20', s=30)
axes[0,0].set_title('PCA 2D - True Genres')
axes[0,1].scatter(latent_tsne[:,0], latent_tsne[:,1], c=y_train[:500], cmap='tab20', s=30)
axes[0,1].set_title('t-SNE - True Genres')
axes[0,2].scatter(latent_umap[:,0], latent_umap[:,1], c=y_train, cmap='tab20', s=30)
axes[0,2].set_title('UMAP - True Genres')

# Row 2: Colored by K-Means clusters
axes[1,0].scatter(latent_pca2[:,0], latent_pca2[:,1], c=labels_cvae, cmap='tab20', s=30)
axes[1,0].set_title('PCA 2D - Clusters')
axes[1,1].scatter(latent_tsne[:,0], latent_tsne[:,1], c=labels_cvae[:500], cmap='tab20', s=30)
axes[1,1].set_title('t-SNE - Clusters')
axes[1,2].scatter(latent_umap[:,0], latent_umap[:,1], c=labels_cvae, cmap='tab20', s=30)
axes[1,2].set_title('UMAP - Clusters')

plt.suptitle('Hard Task: CVAE Latent Space Visualizations', fontsize=16)
plt.tight_layout()
plt.show()

"""Cluster distribution over genres"""

contingency = pd.crosstab(y_train, clustering_beta_vae['K-Means'])
sns.heatmap(contingency, annot=True, cmap='Blues')
plt.title('Cluster vs Genre Distribution')
plt.xlabel('Clusters')
plt.ylabel('Genres')
plt.show()

"""Cell 14: Reconstruction"""

with torch.no_grad():
    idxs = np.random.choice(len(X_hybrid), 6, replace=False)
    x_sample = X_tensor[idxs]
    cond_sample = y_tensor[idxs]
    recon, _, _ = cvae(x_sample, cond_sample)

fig, axes = plt.subplots(6, 2, figsize=(12, 18))
for i, idx in enumerate(idxs):
    axes[i,0].plot(X_hybrid[idx], label='Original')
    axes[i,0].set_title(f'Original - {genre_names[y_train[idx]]}')
    axes[i,1].plot(recon[i].numpy(), label='Reconstructed', color='orange')
    axes[i,1].set_title('CVAE Reconstruction')
plt.tight_layout()
plt.show()

"""Done! hurrahh!"""