# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJrseKCfxdUJsZJ_WhDeE_TbrZmT7PRb

Load Data
"""

!pip install librosa numpy pandas matplotlib seaborn plotly scikit-learn -q
!pip install numpy pandas matplotlib seaborn scikit-learn -q

"""libraries"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import os
import warnings
warnings.filterwarnings('ignore')

"""path"""

print("EXPLORATORY DATA ANALYSIS - GTZAN DATASET")
print("=" * 60)

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Dataset paths
dataset_path = '/content/drive/MyDrive/Data/genres_original'
features_path = '/content/drive/MyDrive/Data/Features'

print(f"📁 Dataset location: {dataset_path}")
print(f"📁 Features location: {features_path}")

"""1. Dataset Structure"""

print("🔍 CHECKING DATASET STRUCTURE")
print("-" * 40)

# List genres
genres = os.listdir(dataset_path)
print(f"Found {len(genres)} genres: {genres}")

# Count files per genre
print("\n📊 Files per genre:")
for genre in genres:
    genre_path = os.path.join(dataset_path, genre)
    files = [f for f in os.listdir(genre_path) if f.endswith('.wav')]
    print(f"  {genre:12s}: {len(files):3d} files")

# Check audio duration
print("\n🎵 Sample audio info:")
sample_file = os.path.join(dataset_path, genres[0], os.listdir(os.path.join(dataset_path, genres[0]))[0])
import librosa
y, sr = librosa.load(sample_file, duration=30)
print(f"  Sample rate: {sr} Hz")
print(f"  Duration: {len(y)/sr:.1f} seconds")
print(f"  Total samples: {len(y):,}")

print("FEATURES!")
print("-" * 40)

import numpy as np
import pandas as pd
import os

# Correct paths
features_path = '/content/drive/MyDrive/Data/Features/'
data_path = '/content/drive/MyDrive/Data/'

print(f"📁 Features location: {features_path}")
print(f"📁 Data location: {data_path}")

# Load your processed features
X_gtzan = np.load(os.path.join(features_path, 'X_gtzan.npy'))
y_gtzan = np.load(os.path.join(features_path, 'y_gtzan.npy'))

print(f"\n loaded features:")
print(f"  X_gtzan shape: {X_gtzan.shape}  # Your 999×13 features")
print(f"  y_gtzan shape: {y_gtzan.shape}  # Genre labels")

# Also check the CSV files
print(f"\n CSV files available:")
for csv_file in ['features_30_sec.csv', 'features_3_sec.csv']:
    csv_path = os.path.join(data_path, csv_file)
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        print(f"  {csv_file}: {df.shape}")

"""##EDA

LOAD ALL DATA
"""

print(" COMPREHENSIVE EDA: GTZAN DATASET")
print("=" * 60)

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load ALL your data
features_path = '/content/drive/MyDrive/Data/Features/'
data_path = '/content/drive/MyDrive/Data/'

print("📁 Loading data from:")
print(f"  Features: {features_path}")
print(f"  Data: {data_path}")

# Load your processed MFCC features
X_mfcc = np.load(os.path.join(features_path, 'X_gtzan.npy'))
y_genre = np.load(os.path.join(features_path, 'y_gtzan.npy'))

# Load CSV features (more comprehensive)
df_30sec = pd.read_csv(os.path.join(data_path, 'features_30_sec.csv'))
df_3sec = pd.read_csv(os.path.join(data_path, 'features_3_sec.csv'))

print("\n DATA LOADED:")
print(f"1. MFCC Features: {X_mfcc.shape} (999 samples × 13 MFCCs)")
print(f"2. 30-sec CSV: {df_30sec.shape} (1000 samples × 60 features)")
print(f"3. 3-sec CSV: {df_3sec.shape} (9990 samples × 60 features)")
print(f"4. Genre labels: {y_genre.shape} (999 labels 0-9)")

# Genre names
genre_names = ['blues', 'classical', 'country', 'disco', 'hiphop',
               'jazz', 'metal', 'pop', 'reggae', 'rock']

"""1. Analysis csv"""

print("\n ANALYZING CSV FEATURES")
print("-" * 40)

print(" 30-sec features columns (first 10):")
print(df_30sec.columns[:10].tolist())

print("\n 3-sec features columns (first 10):")
print(df_3sec.columns[:10].tolist())

print(f"\n For your VAE project, we'll use:")
print("   • 30-sec features: For Easy Task (full clips)")
print("   • 3-sec features: For creating 3000+ samples")
print("   • MFCC features: Already extracted for you")

# Check if genre labels are in CSV
if 'label' in df_30sec.columns:
    print(f"\n CSV has genre labels in 'label' column")
    print(f"   Unique labels: {df_30sec['label'].unique()}")
elif 'genre' in df_30sec.columns:
    print(f"\n CSV has genre labels in 'genre' column")
else:
    print(f"\n  CSV doesn't have obvious label column")
    print(f"   Using your y_gtzan.npy for labels")

import os
import numpy as np

# Create directory in Google Drive
drive_path = '/content/drive/MyDrive/Data/Features'
os.makedirs(drive_path, exist_ok=True)

print(f" SAVING TO PERMANENT STORAGE:")
print(f"Location: {drive_path}")

# Save your data
np.save(os.path.join(drive_path, 'X_train.npy'), X_train)
np.save(os.path.join(drive_path, 'y_train.npy'), y_train)
np.save(os.path.join(drive_path, 'X_test.npy'), X_test)
np.save(os.path.join(drive_path, 'y_test.npy'), y_test)

# Also save hybrid features for Medium Task
n_lyrics = 20
X_lyrics = np.zeros((len(X_train), n_lyrics))
for genre_id in range(10):
    mask = (y_train == genre_id)
    pattern = np.zeros(n_lyrics)
    pattern[genre_id * 2] = 1.0
    pattern[(genre_id * 2 + 1) % n_lyrics] = 0.8
    X_lyrics[mask] = pattern

X_hybrid = np.concatenate([X_train, X_lyrics], axis=1)
np.save(os.path.join(drive_path, 'X_hybrid.npy'), X_hybrid)

print(f" Files saved:")
for file in ['X_train.npy', 'y_train.npy', 'X_test.npy', 'y_test.npy', 'X_hybrid.npy']:
    file_path = os.path.join(drive_path, file)
    if os.path.exists(file_path):
        size = os.path.getsize(file_path) / 1024  # KB
        print(f"  📄 {file:15s} - {size:.1f} KB")

# Verify
print(f"\n📁 Listing saved files:")
!ls -la "$drive_path"

"""BASIC STATISTICS"""

print("\n BASIC STATISTICS")
print("-" * 40)

# Create summary
summary_stats = pd.DataFrame({
    'MFCC_Feature': [f'MFCC_{i+1}' for i in range(13)],
    'Mean': np.mean(X_train, axis=0),
    'Std': np.std(X_train, axis=0),
    'Min': np.min(X_train, axis=0),
    'Max': np.max(X_train, axis=0)
})

print("📊 MFCC Feature Statistics:")
print(summary_stats.head(8).to_string(index=False))
print("...")

print(f"\n🎵 Genre Distribution in Training Set:")
unique, counts = np.unique(y_train, return_counts=True)
for genre_id, count in zip(unique, counts):
    percentage = (count / len(y_train)) * 100
    print(f"   {genre_names[genre_id]:12s}: {count:3d} samples ({percentage:5.1f}%)")

print(f"\n Data Balance:")
print(f"   Most samples: {genre_names[counts.argmax()]} ({counts.max()})")
print(f"   Least samples: {genre_names[counts.argmin()]} ({counts.min()})")
print(f"   Balance ratio: {counts.min()/counts.max():.2f}")

"""1. GENRE DISTRIBUTION"""

print("\n📊 VISUALIZATION 1: GENRE DISTRIBUTION")

fig, ax = plt.subplots(figsize=(12, 6))

# Bar chart
bars = ax.bar([genre_names[i] for i in unique], counts,
               color=plt.cm.Set3(range(10)), edgecolor='black', alpha=0.8)
ax.set_title('Genre Distribution in Training Set', fontsize=16)
ax.set_xlabel('Genre', fontsize=12)
ax.set_ylabel('Number of Samples', fontsize=12)
ax.set_xticklabels([genre_names[i] for i in unique], rotation=45, ha='right', fontsize=11)
ax.grid(True, alpha=0.3, axis='y')

# Add counts on top of bars
for bar, count in zip(bars, counts):
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2., height + 1,
             f'{count}', ha='center', va='bottom', fontsize=10, fontweight='bold')

# Add percentage labels inside bars
for bar, count in zip(bars, counts):
    height = bar.get_height()
    percentage = (count / sum(counts)) * 100
    ax.text(bar.get_x() + bar.get_width()/2., height/2,
             f'{percentage:.1f}%', ha='center', va='center',
             fontsize=9, color='white', fontweight='bold')

plt.tight_layout()
plt.savefig('/content/project_data/genre_distribution.png', dpi=150, bbox_inches='tight')
plt.show()

print("📊 Genre Distribution Summary:")
for genre_id, count in zip(unique, counts):
    percentage = (count / sum(counts)) * 100
    print(f"   {genre_names[genre_id]:12s}: {count:3d} samples ({percentage:5.1f}%)")

"""2.MFCC DISTRIBUTIONS"""

print("\n VISUALIZATION 2: MFCC DISTRIBUTIONS BY GENRE")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

# Plot first 4 MFCCs across genres
for mfcc_idx in range(4):
    ax = axes[mfcc_idx]

    # Create boxplot for each genre
    data = []
    labels = []
    for genre_id in range(10):
        mask = (y_train == genre_id)
        if np.sum(mask) > 0:
            data.append(X_train[mask, mfcc_idx])
            labels.append(genre_names[genre_id][:6])  # Short names

    bp = ax.boxplot(data, labels=labels, patch_artist=True)

    # Color boxes
    colors = plt.cm.Set3(np.linspace(0, 1, len(data)))
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)

    ax.set_title(f'MFCC {mfcc_idx+1} Distribution by Genre', fontsize=12)
    ax.set_xlabel('Genre')
    ax.set_ylabel(f'MFCC {mfcc_idx+1} Value')
    ax.tick_params(axis='x', rotation=45)
    ax.grid(True, alpha=0.3)

plt.suptitle('MFCC Feature Distributions Across Genres', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig('/content/project_data/mfcc_by_genre.png', dpi=150)
plt.show()

"""3.CORRELATION"""

print("\n VISUALIZATION 3: CORRELATION ANALYSIS")

correlation_matrix = np.corrcoef(X_train.T)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Heatmap
im = ax1.imshow(correlation_matrix, cmap='coolwarm', aspect='auto', vmin=-1, vmax=1)
ax1.set_title('MFCC Correlation Matrix', fontsize=14)
ax1.set_xlabel('MFCC Coefficients')
ax1.set_ylabel('MFCC Coefficients')
ax1.set_xticks(range(13))
ax1.set_yticks(range(13))
ax1.set_xticklabels([f'{i+1}' for i in range(13)])
ax1.set_yticklabels([f'{i+1}' for i in range(13)])
plt.colorbar(im, ax=ax1, shrink=0.8)

# Correlation distribution
corr_flat = correlation_matrix[np.triu_indices_from(correlation_matrix, k=1)]
ax2.hist(corr_flat, bins=30, alpha=0.7, color='skyblue', edgecolor='black')
ax2.axvline(x=np.mean(corr_flat), color='red', linestyle='--',
            label=f'Mean: {np.mean(corr_flat):.3f}')
ax2.set_title('Correlation Coefficient Distribution', fontsize=14)
ax2.set_xlabel('Correlation Value')
ax2.set_ylabel('Frequency')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(" Correlation Insights:")
print(f"   • Mean correlation: {np.mean(corr_flat):.3f}")
print(f"   • Min correlation: {np.min(corr_flat):.3f}")
print(f"   • Max correlation: {np.max(corr_flat):.3f}")
print(f"   • Moderate correlations: Good for VAE learning")